---
title: "Hvorfor er ikke Checkpoint/renv nok til å sikre reproduserbarhet?"
author: "esknu, marma-gest, Rrbracci"
format:
  revealjs:
        theme: simple
        reveal_options:
        code-fold: show
        incremental: true
        smaller: true
        scrollable: true
        slide-number: c/t
editor: visual
editor_options:
  markdown:
    wrap: 72
    canonical: true
    chunk_output_type: console
echo: true
eval: true
bibliography: reproducibility.bib
nocite: '@*'
---

## Innhold

-   Checkpoint/renv

    -   Hva er checkpoint?

        -   Det er....

        -   Hvorfor ikke reproduserbart?

            -   

-   Docker

    -   Hva er Docker?

    -   Hvofor kan Docker sikre økt reproduserbarhet?

-   Er Docker «over-kill»?

    1)  First underpoint
    2)  Second underpoint

-   Second point

. . .

For å sikre at ting venter med å bli vist bruk Slide Pause fra Insert
menyen. Vises som ... i Quarto presentasjonen, men er usynlig i den
endelige presentasjonen.

## Checkpoint/renv

-   
-   Hvis en har incremental: true i YAML kan en få en liste til å bli
    nonincremental ved å benytte en Div (Div... fra Insert menyen)
-   Lag Div-en. Klikk de tre prikkene til høyre. Skriv inn
    `.nonincremental` for class (`.incremental` hvis en ikke har
    incremental som default)

. . .

::: nonincremental
-   First point

    1)  First underpoint
    2)  Second underpoint

-   Second point
:::

## Slide 3

-   Content authored with markdown
-   Output from executable code.

## Referanser
